name: "Install Nix"
description: "Install Nix using the experimental nix-installer"

inputs:
  installer-version:
    description: "Installer version to use from releases (default: latest)"
    required: false
    default: "latest"
  extra-conf:
    description: "Extra configuration lines to append to /etc/nix/nix.conf"
    required: false
    default: ""
  logger:
    description: "Logger format: compact, full, pretty, json"
    required: false
    default: "compact"
  verbosity:
    description: "Verbosity level: 0 (info), 1 (debug), 2 (trace)"
    required: false
    default: "0"
  add-channel:
    description: "Setup the default system channels"
    required: false
    default: "false"
  dogfood:
    description: "Use a locally built installer instead of downloading from releases (for CI)"
    required: false
    default: "false"
  dogfood-path:
    description: "Path to the locally built installer (used with dogfood)"
    required: false
    default: ""
  init:
    description: "Init system configuration: auto (detect container), yes (use systemd/launchd), no (manual daemon)"
    required: false
    default: "auto"
  trust-runner-user:
    description: "Add the current user to trusted-users in nix.conf"
    required: false
    default: "true"
  enable-kvm:
    description: "Enable KVM for hardware-accelerated virtualization on Linux runners"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Detect platform
      shell: bash
      id: platform
      run: |
        RUNNER_OS_LOWER="$(printf '%s' "$RUNNER_OS" | tr '[:upper:]' '[:lower:]')"
        RUNNER_ARCH_LOWER="$(printf '%s' "$RUNNER_ARCH" | tr '[:upper:]' '[:lower:]')"

        case "$RUNNER_OS_LOWER" in
          linux)
            OS_PART="linux"
            ;;
          macos)
            OS_PART="darwin"
            ;;
          *)
            echo "::error ::Unsupported RUNNER_OS: $RUNNER_OS. Supported: Linux, macOS"
            exit 1
            ;;
        esac

        case "$RUNNER_ARCH_LOWER" in
          x64)
            ARCH_PART="x86_64"
            ;;
          arm64)
            ARCH_PART="aarch64"
            ;;
          arm)
            ARCH_PART="armv7l"
            ;;
          *)
            echo "::error ::Unsupported RUNNER_ARCH: $RUNNER_ARCH. Supported: X64, ARM64, ARM"
            exit 1
            ;;
        esac

        INSTALLER_SYSTEM="${ARCH_PART}-${OS_PART}"
        echo "system=$INSTALLER_SYSTEM" >> "$GITHUB_OUTPUT"
        echo "os=$OS_PART" >> "$GITHUB_OUTPUT"
        echo "Detected platform: $INSTALLER_SYSTEM (OS=$RUNNER_OS, ARCH=$RUNNER_ARCH)"

    - name: Detect init system
      shell: bash
      id: init
      run: |
        INIT_INPUT="${{ inputs.init }}"

        if [ "$INIT_INPUT" = "yes" ]; then
          USE_INIT="yes"
          echo "Init mode: yes (explicit)"
        elif [ "$INIT_INPUT" = "no" ]; then
          USE_INIT="no"
          echo "Init mode: no (explicit)"
        else
          # Auto-detect: check if systemd is PID 1
          if [ "${{ steps.platform.outputs.os }}" = "linux" ]; then
            PID1_COMM="$(cat /proc/1/comm 2>/dev/null || echo unknown)"
            if [ "$PID1_COMM" = "systemd" ]; then
              USE_INIT="yes"
              echo "Init mode: yes (auto-detected systemd as PID 1)"
            else
              USE_INIT="no"
              echo "Init mode: no (auto-detected container, PID 1 is '$PID1_COMM')"
            fi
          else
            # macOS always uses launchd
            USE_INIT="yes"
            echo "Init mode: yes (macOS uses launchd)"
          fi
        fi

        echo "use_init=$USE_INIT" >> "$GITHUB_OUTPUT"

    - name: Download installer from release
      shell: bash
      id: download
      run: |
        SYSTEM="${{ steps.platform.outputs.system }}"
        BINARY_NAME="nix-installer-${SYSTEM}"

        if [ "${{ inputs.dogfood }}" == "true" ]; then
          DOGFOOD_PATH="${{ inputs.dogfood-path }}"
          if [ -z "$DOGFOOD_PATH" ]; then
            echo "::error ::dogfood is enabled but dogfood-path is not set"
            exit 1
          fi

          INSTALLER_DIR="$DOGFOOD_PATH"
          if [ ! -f "$INSTALLER_DIR/$BINARY_NAME" ]; then
            echo "::error ::Installer binary not found at: $INSTALLER_DIR/$BINARY_NAME"
            exit 1
          fi

          chmod +x "$INSTALLER_DIR/$BINARY_NAME"
          echo "path=$INSTALLER_DIR" >> "$GITHUB_OUTPUT"
          echo "Using locally built installer: $INSTALLER_DIR/$BINARY_NAME"
        else
          VERSION="${{ inputs.installer-version }}"
          INSTALLER_DIR="/tmp/nix-installer"

          mkdir -p "$INSTALLER_DIR"

          echo "Downloading nix-installer $VERSION for $SYSTEM from GitHub releases"

          if [ "$VERSION" == "latest" ]; then
            DOWNLOAD_URL="https://github.com/NixOS/nix-installer/releases/latest/download/${BINARY_NAME}"
          else
            DOWNLOAD_URL="https://github.com/NixOS/nix-installer/releases/download/${VERSION}/${BINARY_NAME}"
          fi

          echo "Downloading from: $DOWNLOAD_URL"
          curl -L -f -o "$INSTALLER_DIR/$BINARY_NAME" "$DOWNLOAD_URL"

          if [ $? -ne 0 ] || [ ! -f "$INSTALLER_DIR/$BINARY_NAME" ]; then
            echo "::error ::Failed to download installer binary: $BINARY_NAME"
            echo "::error ::Version: $VERSION"
            echo "::error ::Check available releases: https://github.com/NixOS/nix-installer/releases"
            exit 1
          fi

          chmod +x "$INSTALLER_DIR/$BINARY_NAME"
          echo "path=$INSTALLER_DIR" >> "$GITHUB_OUTPUT"
          echo "Downloaded installer to: $INSTALLER_DIR/$BINARY_NAME"
        fi

    - name: Enable KVM
      shell: bash
      if: runner.os == 'Linux' && inputs.enable-kvm == 'true'
      run: |
        if [ -e /dev/kvm ]; then
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' \
            | sudo tee /etc/udev/rules.d/99-nix-installer-kvm.rules
          sudo udevadm control --reload-rules && sudo udevadm trigger --name-match=kvm
          echo "KVM enabled"
        else
          echo "KVM not available on this runner"
        fi

    - name: Run nix-installer
      shell: bash
      env:
        NIX_INSTALLER_NO_CONFIRM: "true"
      run: |
        set -x
        INSTALLER_DIR="${{ steps.download.outputs.path }}"
        SYSTEM="${{ steps.platform.outputs.system }}"
        INSTALLER_BINARY="$INSTALLER_DIR/nix-installer-$SYSTEM"

        if [ ! -f "$INSTALLER_BINARY" ]; then
          echo "::error ::Installer binary not found: $INSTALLER_BINARY"
          exit 1
        fi

        INSTALL_ARGS=(--no-confirm --explain)

        if [ -n "${{ inputs.logger }}" ] && [ "${{ inputs.logger }}" != "compact" ]; then
          INSTALL_ARGS+=(--logger "${{ inputs.logger }}")
        fi

        case "${{ inputs.verbosity }}" in
          1)
            INSTALL_ARGS+=(-v)
            ;;
          2)
            INSTALL_ARGS+=(-vv)
            ;;
        esac

        if [ "${{ inputs.add-channel }}" == "true" ]; then
          INSTALL_ARGS+=(--add-channel)
        fi

        if [ "${{ steps.init.outputs.use_init }}" = "no" ]; then
          INSTALL_ARGS+=(--init none)
        fi

        # Build extra-conf with optional trusted-users and KVM support
        EXTRA_CONF=""
        if [ "${{ inputs.trust-runner-user }}" == "true" ]; then
          EXTRA_CONF="trusted-users = root $USER"
        fi
        if [ "${{ inputs.enable-kvm }}" == "true" ] && [ -e /dev/kvm ]; then
          EXTRA_CONF="$EXTRA_CONF"$'\n'"extra-system-features = kvm"
        fi
        if [ -n "${{ inputs.extra-conf }}" ]; then
          if [ -n "$EXTRA_CONF" ]; then
            EXTRA_CONF="$EXTRA_CONF"$'\n'"${{ inputs.extra-conf }}"
          else
            EXTRA_CONF="${{ inputs.extra-conf }}"
          fi
        fi
        if [ -n "$EXTRA_CONF" ]; then
          INSTALL_ARGS+=(--extra-conf "$EXTRA_CONF")
        fi

        case "${{ steps.platform.outputs.os }}" in
          linux)
            PLANNER="linux"
            ;;
          darwin)
            PLANNER=""
            ;;
          *)
            echo "::error ::Unsupported RUNNER_OS: $RUNNER_OS"
            exit 1
            ;;
        esac

        echo "::group::Installation command"
        echo "PLANNER: '$PLANNER'"
        echo "add-channel input: ${{ inputs.add-channel }}"
        if [ -n "$PLANNER" ]; then
          echo "Full command: sudo $INSTALLER_BINARY install $PLANNER ${INSTALL_ARGS[@]}"
        else
          echo "Full command: sudo $INSTALLER_BINARY install ${INSTALL_ARGS[@]}"
        fi
        echo "::endgroup::"

        echo "Starting Nix installation..."
        if [ -n "$PLANNER" ]; then
          sudo "$INSTALLER_BINARY" install "$PLANNER" "${INSTALL_ARGS[@]}"
        else
          sudo "$INSTALLER_BINARY" install "${INSTALL_ARGS[@]}"
        fi

        if [ $? -ne 0 ]; then
          echo "::error ::nix-installer failed"
          exit 1
        fi

        # Set per user profile
        if [ -n "${NIX_STATE_HOME-}" ]; then
            NIX_LINK="$NIX_STATE_HOME/profile"
        else
            NIX_LINK="$HOME/.nix-profile"
            if [ -n "${XDG_STATE_HOME-}" ]; then
                NIX_LINK_NEW="$XDG_STATE_HOME/nix/profile"
            else
                NIX_LINK_NEW="$HOME/.local/state/nix/profile"
            fi
            if [ -e "$NIX_LINK_NEW" ]; then
                if [ -t 2 ] && [ -e "$NIX_LINK" ]; then
                    warning="\033[1;35mwarning:\033[0m"
                    printf "$warning Both %s and legacy %s exist; using the former.\n" "$NIX_LINK_NEW" "$NIX_LINK" 1>&2
                fi
                NIX_LINK="$NIX_LINK_NEW"
            fi
        fi
        echo "NIX_PROFILES=/nix/var/nix/profiles/default $NIX_LINK" >>"$GITHUB_ENV"
        echo "Nix installation completed successfully"

    - name: Start nix-daemon manually (for no-init environments)
      shell: bash
      if: steps.init.outputs.use_init == 'no' && runner.os == 'Linux'
      run: |
        echo "Starting nix-daemon manually (no-init mode)..."
        sudo /nix/var/nix/profiles/default/bin/nix-daemon &

        for i in {1..300}; do
          if [ -S /nix/var/nix/daemon-socket/socket ]; then
            echo "nix-daemon is ready"
            break
          fi
          sleep 0.1
        done

        if [ ! -S /nix/var/nix/daemon-socket/socket ]; then
          echo "::error ::nix-daemon socket not available after 30 seconds"
          exit 1
        fi

    - name: Setup Nix in PATH
      shell: bash
      run: |
        echo "/nix/var/nix/profiles/default/bin" >> "$GITHUB_PATH"
        echo "$HOME/.nix-profile/bin" >> "$GITHUB_PATH"

        if [ -f /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh ]; then
          . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
        fi

        if command -v nix >/dev/null 2>&1; then
          NIX_VERSION=$(nix --version)
          echo "Nix is ready: $NIX_VERSION"
        else
          echo "nix command not immediately available in PATH."
          exit 1
        fi
